# Generated by Django 5.1.3 on 2025-01-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('consulate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipientCountries',
            field=models.ManyToManyField(related_name='messages', to='common.country'),
        ),
    ]
