# Generated by Django 5.1.3 on 2025-01-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_clientdata_resides_in_clientdata_resides_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='pesel',
            field=models.CharField(max_length=11),
        ),
    ]
