# Generated by Django 5.1.3 on 2024-12-11 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odysseus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripwarning',
            name='trip_stage',
        ),
        migrations.AddField(
            model_name='tripwarning',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='odysseus.country'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='consulate',
            name='managed_country',
        ),
        migrations.AddField(
            model_name='consulate',
            name='managed_country',
            field=models.ManyToManyField(related_name='consulates', to='odysseus.country'),
        ),
    ]
