# Generated by Django 5.1.3 on 2024-12-11 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odysseus', '0002_remove_tripwarning_trip_stage_tripwarning_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='odysseus.consulateemployee'),
            preserve_default=False,
        ),
    ]
