# Generated by Django 5.1.3 on 2024-12-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odysseus', '0003_message_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleteTripAfterDays', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
