BEGIN;

-- Create model Address
CREATE TABLE "odysseus_address" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "street" varchar(255) NOT NULL,
    "building_number" varchar(50) NOT NULL,
    "apartment_number" varchar(50) NULL,
    "locality" varchar(255) NOT NULL
);

-- Create model Country
CREATE TABLE "odysseus_country" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "code" varchar(10) NOT NULL UNIQUE,
    "name" varchar(255) NOT NULL
);

-- Create model Recipient
CREATE TABLE "odysseus_recipient" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "status" varchar(10) NOT NULL,
    "phone_number" varchar(20) NOT NULL
);

-- Create model StayOrganizer
CREATE TABLE "odysseus_stayorganizer" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "name" varchar(255) NULL,
    "type" varchar(20) NOT NULL
);

-- Create model TripStagesStatistic
CREATE TABLE "odysseus_tripstagesstatistic" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "month" integer NOT NULL,
    "year" integer NOT NULL,
    "trip_count" integer NOT NULL
);

-- Create model Consulate
CREATE TABLE "odysseus_consulate" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "name" varchar(255) NOT NULL,
    "address_id" integer NOT NULL UNIQUE
);

-- Create model ConsulateEmployee
CREATE TABLE "odysseus_consulateemployee" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "name" varchar(255) NOT NULL,
    "surname" varchar(255) NOT NULL,
    "employee_of_id" integer NOT NULL
);

-- Create model ClientData
CREATE TABLE "odysseus_clientdata" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "name" varchar(50) NOT NULL,
    "surname" varchar(50) NOT NULL,
    "pesel" varchar(11) NOT NULL UNIQUE,
    "phone_number" varchar(20) NOT NULL,
    "email_address" varchar(254) NOT NULL,
    "address_id" integer NOT NULL UNIQUE
);

CREATE TABLE "odysseus_clientdata_resides_in" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "clientdata_id" integer NOT NULL,
    "country_id" integer NOT NULL
);

-- Create model Message
CREATE TABLE "odysseus_message" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "content" text NOT NULL,
    "date" date NOT NULL,
    "author_id" integer NOT NULL
);

CREATE TABLE "odysseus_message_recipients" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "message_id" integer NOT NULL,
    "recipient_id" integer NOT NULL
);

-- Create model Trip
CREATE TABLE "odysseus_trip" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "client_data_id" integer NOT NULL
);

-- Create model TripStage
CREATE TABLE "odysseus_tripstage" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "arrival_date" date NOT NULL,
    "departure_date" date NOT NULL,
    "address_id" integer NOT NULL,
    "country_id" integer NOT NULL,
    "stay_organizer_id" integer NULL,
    "trip_id" integer NOT NULL
);

-- Create model TripWarning
CREATE TABLE "odysseus_tripwarning" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "content" text NOT NULL,
    "country_id" integer NOT NULL
);

-- Create model Parameters
CREATE TABLE "odysseus_parameters" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "deleteTripAfterDays" integer NOT NULL
);

-- Foreign key constraints
ALTER TABLE "odysseus_consulate" ADD CONSTRAINT "fk_consulate_address" FOREIGN KEY ("address_id") REFERENCES "odysseus_address" ("id");
ALTER TABLE "odysseus_consulateemployee" ADD CONSTRAINT "fk_consulateemployee_consulate" FOREIGN KEY ("employee_of_id") REFERENCES "odysseus_consulate" ("id");
ALTER TABLE "odysseus_clientdata" ADD CONSTRAINT "fk_clientdata_address" FOREIGN KEY ("address_id") REFERENCES "odysseus_address" ("id");
ALTER TABLE "odysseus_clientdata_resides_in" ADD CONSTRAINT "fk_clientdata_country" FOREIGN KEY ("country_id") REFERENCES "odysseus_country" ("id");
ALTER TABLE "odysseus_message" ADD CONSTRAINT "fk_message_author" FOREIGN KEY ("author_id") REFERENCES "odysseus_consulateemployee" ("id");
ALTER TABLE "odysseus_trip" ADD CONSTRAINT "fk_trip_clientdata" FOREIGN KEY ("client_data_id") REFERENCES "odysseus_clientdata" ("id");
ALTER TABLE "odysseus_tripstage" ADD CONSTRAINT "fk_tripstage_address" FOREIGN KEY ("address_id") REFERENCES "odysseus_address" ("id");
ALTER TABLE "odysseus_tripstage" ADD CONSTRAINT "fk_tripstage_country" FOREIGN KEY ("country_id") REFERENCES "odysseus_country" ("id");
ALTER TABLE "odysseus_tripwarning" ADD CONSTRAINT "fk_tripwarning_country" FOREIGN KEY ("country_id") REFERENCES "odysseus_country" ("id");

COMMIT;