# Generated by Django 5.1.3 on 2025-01-18 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('registration', '0002_remove_clientdata_resides_in_clientdata_resides_in'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='client_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='registration.clientdata'),
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.address'),
        ),
    ]
